### ISSUE TITLE
Panic in gtksink example

### ISSUE THREAD

**Issue by thatcodeguy** [sdroege/gstreamer-rs#19]
```
$ RUST_BACKTRACE=1 ./gtksink.exe
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::option::Option<T>>::unwrap
             at C:\projects\rust\src\libcore/macros.rs:22
  10: gtksink::create_ui
             at src\bin/gtksink.rs:29
  11: core::ops::function::Fn::call
             at C:\projects\rust\src\libcore\ops/function.rs:48
  12: gio::auto::application::activate_trampoline
             at C:\Users\xx\.cargo\git\checkouts\gio-a4b825b310a073b9\4c69584\src\auto/application.rs:491
  13: unit_addrs_search
  14: unit_addrs_search
  15: unit_addrs_search
  16: unit_addrs_search
  17: unit_addrs_search
  18: unit_addrs_search
  19: <O as gio::auto::application::ApplicationExt>::run
             at C:\Users\xx\.cargo\git\checkouts\gio-a4b825b310a073b9\4c69584\src\auto/application.rs:297
  20: gtksink::main
             at src\bin/gtksink.rs:123
  21: _rust_maybe_catch_panic
  22: std::rt::lang_start
  23: main
  24: _tmainCRTStartup
  25: mainCRTStartup
  26: unit_addrs_search
```
Am I missing something obvious here?

`nightly-x86_64-pc-windows-gnu` is the target.

**Comment by sdroege** [comment]
That's because you don't have the `gtksink` element unfortunately, or `gtkglsink`. These are currently not shipped with the GStreamer binaries for Windows and macOS. Proper error handling (https://github.com/sdroege/gstreamer-rs/issues/2) would've made that more obvious.

You would have to build that GStreamer element yourself for now, it can be found here: https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/ext/gtk

**Comment by thatcodeguy** [comment]
I'm using MSYS2 and installing the `mingw-w64-x86_64-gst-plugins-bad` package fixed it for me.

**Comment by sdroege** [comment]
Ah good to know that msys actually ships that :) Thanks for letting me know
